import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Wristband',
    description: 'A stylish and comfortable wristband for everyday wear.',
    price: 15.99,
    image: 'https://picsum.photos/seed/wristband/400/400',
    imageHint: 'wristband fashion',
    category: 'Wristband',
  },
  {
    id: '2',
    name: 'Elegant Timepiece',
    description: 'A sophisticated wristwatch that complements any outfit.',
    price: 120.5,
    image: 'https://picsum.photos/seed/wristwatch/400/400',
    imageHint: 'wristwatch elegant',
    category: 'Wristwatch',
  },
  {
    id: '3',
    name: 'Silver Charm Bracelet',
    description: 'A beautiful silver bracelet with delicate charms.',
    price: 45.0,
    image: 'https://picsum.photos/seed/bracelet/400/400',
    imageHint: 'bracelet jewelry',
    category: 'Bracelet',
  },
  {
    id: '4',
    name: 'Minimalist Leather Wallet',
    description: 'A sleek wallet made from genuine leather.',
    price: 35.0,
    image: 'https://picsum.photos/seed/wallet/400/400',
    imageHint: 'leather wallet',
    category: 'Wallet',
  },
  {
    id: '5',
    name: 'Classic Leather Belt',
    description: 'A durable and timeless leather belt.',
    price: 25.0,
    image: 'https://picsum.photos/seed/belt/400/400',
    imageHint: 'leather belt',
    category: 'Belt',
  },
  {
    id: '6',
    name: 'Urban Explorer Cap',
    description: 'A trendy cap for your urban adventures.',
    price: 22.99,
    image: 'https://picsum.photos/seed/cap/400/400',
    imageHint: 'fashion cap',
    category: 'Cap',
  },
  {
    id: '7',
    name: 'Diamond Stud Earrings',
    description: 'A pair of sparkling diamond stud earrings.',
    price: 250.0,
    image: 'https://picsum.photos/seed/earring/400/400',
    imageHint: 'earrings jewelry',
    category: 'Earring',
  },
  {
    id: '8',
    name: 'Shimmering Lip Gloss',
    description: 'A high-shine lip gloss for a luscious look.',
    price: 12.0,
    image: 'https://picsum.photos/seed/lipgloss/400/400',
    imageHint: 'lip gloss',
    category: 'Lip glosses',
  },
  {
    id: '9',
    name: 'Nourishing Hand Cream',
    description: 'A rich and moisturizing hand cream with a pleasant scent.',
    price: 8.5,
    image: 'https://picsum.photos/seed/handcream/400/400',
    imageHint: 'hand cream',
    category: 'Hand cream',
  },
];
